### ISSUE TITLE
build error stm32f7

### ISSUE THREAD

**Issue by sonsatthu507** [danieleff/STM32GENERIC#11]
I try build F746NG, it's error.
arm-none-eabi-g++: error: unrecognized argument in option '-mcpu=cortex-m7'. 
How i can fix it?

**Comment by danieleff** [comment]
Download the latest GNU ARM Embedded toolchain from https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
Change `platform.txt` `compiler.path=` to point to that version.

The version included in Arduino is so old it cannot compile to F7

**Comment by sonsatthu507** [comment]
Thank you very much danieleff! I built successfull F7,
