### ISSUE TITLE
Nucleo F030R8 Blink not compiling

### ISSUE THREAD

**Issue by ChrisMicro** [danieleff/STM32GENERIC#12]
First error:
 extern PCD_HandleTypeDef hpcd_USB_FS;
..

**Comment by danieleff** [comment]
This should now be fixed in the master branch.

**Comment by ChrisMicro** [comment]
Compiling and programming with ST-Link now working.
Trying to download  by "Mass Storage" results in:
" NODE_F030R8 not found. Please ensure the device is correctly connected "

**Comment by danieleff** [comment]
If you plug in the board, what is the name of the new drive?

**Comment by ChrisMicro** [comment]
NUCLEO

**Comment by danieleff** [comment]
So drive names for boards:
- Nucleo F411RE: NODE_F411RE
- Nucleo F030R8: NUCLEO
- Discovery L0: DISCOVERY
- Discovery F7: DIS_F746NG

Great... would be good to have a list of all of these.

**Comment by ChrisMicro** [comment]
Hi Daniel,
I just realized that you solved the issue. Great work! 
Thanks,
Chris
